# This is Assignment 06 - Thienkim Le 
## Requirement 4

In [1]:
# Assignment 06: Manipulating Lists

# Create a list named list_1
list_1 = []

# Populate list_1 with 20 arbitrary numbers between 0 and 99
import random
list_1 = [random.randint(0, 99) for _ in range(20)]

# Output the length of the list
print("Length of list_1:", len(list_1))

# Append 3 numbers to the list between 0 and 99
list_1.extend(random.randint(0, 99) for _ in range(3))

# Use the addition operator to append a literal list of 7 numbers between 0 and 99 to list_1
list_1 += [random.randint(0, 99) for _ in range(7)]

# Sort list_1
list_1.sort()

print(list_1)

Length of list_1: 20
[1, 3, 3, 4, 4, 5, 5, 8, 8, 15, 22, 23, 25, 35, 37, 39, 59, 63, 63, 64, 68, 69, 69, 77, 77, 80, 88, 90, 90, 95]

## Requirement 5

In [2]:
# Show the following values from list_1:

# the 4th element
print("4th element:", list_1[3])

# the 15th element
print("15th element:", list_1[14])

# the 3rd element from the end
print("3rd element from the end:", list_1[-3])

# the 7th element from the end
print("7th element from the end:", list_1[-7])

# the first 4 elements
print("First 4 elements:", list_1[:4])

# the last 5 elements
print("Last 5 elements:", list_1[-5:])

# the elements in reverse order
print("Elements in reverse order:", list_1[::-1])

# set the 14th element = -99
list_1[13] = -99
print("List after setting 14th element to -99:", list_1)

# every other (alternating) element in the list
print("Every other element:", list_1[::2])

# set elements 9th through 15th to -77
list_1[8:15] = [-77] * 7
print("List after setting elements 9th through 15th to -77:", list_1)

4th element: 4
15th element: 37
3rd element from the end: 90
7th element from the end: 77
First 4 elements: [1, 3, 3, 4]
Last 5 elements: [80, 88, 90, 90, 95]
Elements in reverse order: [95, 90, 90, 88, 80, 77, 77, 69, 69, 68, 64, 63, 63, 59, 39, 37, 35, 25, 23, 22, 15, 8, 8, 5, 5, 4, 4, 3, 3, 1]
List after setting 14th element to -99: [1, 3, 3, 4, 4, 5, 5, 8, 8, 15, 22, 23, 25, -99, 37, 39, 59, 63, 63, 64, 68, 69, 69, 77, 77, 80, 88, 90, 90, 95]
Every other element: [1, 3, 4, 5, 8, 22, 25, 37, 59, 63, 68, 69, 77, 88, 90]
List after setting elements 9th through 15th to -77: [1, 3, 3, 4, 4, 5, 5, 8, -77, -77, -77, -77, -77, -77, -77, 39, 59, 63, 63, 64, 68, 69, 69, 77, 77, 80, 88, 90, 90, 95]

## Requirement 6

In [3]:
# Create a tuple named tuple_1 containing 7 arbitrary numbers
tuple_1 = (5, 10, 15, 20, 25, 30, 35)

# Attempt to set the 3rd value to -33 (This will raise an error because tuples are immutable)
try:
    tuple_1[2] = -33
except TypeError as e:
    print("Error:", e)

# Attempt to append the value -22 to the tuple (This will raise an error because tuples do not support item assignment)
try:
    tuple_1.append(-22)
except AttributeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment
Error: 'tuple' object has no attribute 'append'

## Requirement 7

In [4]:
# Create a dictionary named players_<sportofchoice> (e.g. players_baseball)
players_baseball = {
    "shortstop": "Brennen",
    "pitcher": "Jack",
    "catcher": "Max",
    "first base": "Ethan",
    "second base": "Luke",
    "third base": "Tyler",
    "left field": "Ryan",
    "center field": "Dylan",
    "right field": "Jake"
}

# Change a key::value pair
players_baseball["left field"] = "Aiden"

# Add a new key::value pair
players_baseball["designated hitter"] = "Mason"

print(players_baseball)

{'shortstop': 'Brennen', 'pitcher': 'Jack', 'catcher': 'Max', 'first base': 'Ethan', 'second base': 'Luke', 'third base': 'Tyler', 'left field': 'Aiden', 'center field': 'Dylan', 'right field': 'Jake', 'designated hitter': 'Mason'}

## Requirement 8

In [5]:
# Create two sets named hatfields and mccoys
hatfields = {"John", "William", "Sarah", "Rebecca", "Emma", "Andrew", "Isaac", "Mary", "Samuel", "Grace"}
mccoys = {"James", "Sarah", "Rebecca", "Emma", "Andrew", "Isaac", "Mary", "Thomas", "Samuel", "Grace"}

# Union of the two sets
union_set = hatfields.union(mccoys)
print("Union:", union_set)

# Intersection of the two sets
intersection_set = hatfields.intersection(mccoys)
print("Intersection:", intersection_set)

# Difference between hatfields and mccoys
difference_set = hatfields.difference(mccoys)
print("Difference (Hatfields - Mccoys):", difference_set)

# Symmetric difference between hatfields and mccoys
symmetric_difference_set = hatfields.symmetric_difference(mccoys)
print("Symmetric Difference:", symmetric_difference_set)

Union: {'Samuel', 'Rebecca', 'Emma', 'James', 'Sarah', 'Isaac', 'John', 'Thomas', 'William', 'Grace', 'Mary', 'Andrew'}
Intersection: {'Samuel', 'Rebecca', 'Emma', 'Sarah', 'Grace', 'Mary', 'Isaac', 'Andrew'}
Difference (Hatfields - Mccoys): {'William', 'John'}
Symmetric Difference: {'Thomas', 'James', 'William', 'John'}

## Requirement 9

In [6]:
# Weather conditions
weather = "rainy"

# Check weather conditions
if weather == "sunny":
    print("It's a sunny day! Don't forget your sunglasses.")
elif weather == "rainy":
    print("It's raining. Don't forget your umbrella.")
elif weather == "cloudy":
    print("It's cloudy today. Might need a light jacket.")
else:
    print("Weather conditions are unknown.")

It's raining. Don't forget your umbrella.

## Requirement 10

In [7]:
# Using a for loop with a range
print("Using a for loop with a range:")
for i in range(5):
    print(i)

# Using a for loop with list contents
print("\nUsing a for loop with list contents:")
names = ["Alice", "Bob", "Charlie", "David", "Eve"]
for name in names:
    print(name)

Using a for loop with a range:
0
1
2
3
4

Using a for loop with list contents:
Alice
Bob
Charlie
David
Eve

## Requirement 11

In [9]:
# Using while loop with i = 0 to 7
print("Using while loop with i = 0 to 7:")
i = 0
while i <= 7:
    print(i)
    i += 1

# Using while loop with i = 1 to 7
print("\nUsing while loop with i = 1 to 7:")
i = 1
while i <= 7:
    print(i)
    i += 1

Using while loop with i = 0 to 7:
0
1
2
3
4
5
6
7

Using while loop with i = 1 to 7:
1
2
3
4
5
6
7

## Requirement 12

In [10]:
def factorial(n):
    """
    Calculates the factorial of a number.
    
    Args:
    n (int): The number to calculate the factorial for.
    
    Returns:
    int: The factorial of the given number.
    """
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Test the factorial function with an example
result = factorial(5)
print("Factorial of 5 is:", result)

Factorial of 5 is: 120

## Requirement 13

In [11]:
def vegetables(*args, **kwargs):
    """
    Prints the numbers and names of vegetables passed as arguments.

    Args:
    *args: Variable-length argument list containing numbers of vegetables.
    **kwargs: Arbitrary keyword arguments containing names of vegetables.
    """
    for i, num_veggies in enumerate(args):
        print(f"Vegetable {i+1}: {num_veggies}")

    for veggie_name, veggie_num in kwargs.items():
        print(f"{veggie_name}: {veggie_num}")


# Example usage of the vegetables function
vegetables(3, 5, 7, potato=2, tomato=4, carrot=3)

Vegetable 1: 3
Vegetable 2: 5
Vegetable 3: 7
potato: 2
tomato: 4
carrot: 3

## Requirement 14

In [13]:
# Create a list named cars with three dictionaries representing attributes of automobiles
cars = [
    {"brand": "Toyota", "model": "Camry", "year": 2022},
    {"brand": "Honda", "model": "Civic", "year": 2020},
    {"brand": "Ford", "model": "Mustang", "year": 2021}
]
print('\n')
# Sort the cars list using a lambda to sort based on the brand
sorted_cars_brand = sorted(cars, key=lambda x: x["brand"])
print("Sorted cars list by brand:", sorted_cars_brand,'\n')

# Sort the cars list using a lambda to sort based on the year
sorted_cars_year = sorted(cars, key=lambda x: x["year"])
print("Sorted cars list by year:", sorted_cars_year,'\n')

Sorted cars list by brand: [{'brand': 'Ford', 'model': 'Mustang', 'year': 2021}, {'brand': 'Honda', 'model': 'Civic', 'year': 2020}, {'brand': 'Toyota', 'model': 'Camry', 'year': 2022}]

Sorted cars list by year: [{'brand': 'Honda', 'model': 'Civic', 'year': 2020}, {'brand': 'Ford', 'model': 'Mustang', 'year': 2021}, {'brand': 'Toyota', 'model': 'Camry', 'year': 2022}]

## Requirement 15

In [14]:
# Function to convert a string to an integer
def convert_to_int(s):
    try:
        result = int(s)
        print("Conversion successful. Integer value:", result)
    except ValueError:
        print("Error: Could not convert to integer. Invalid input!")

# Example usage of the convert_to_int function
convert_to_int("123")   # This should print the integer value 123
convert_to_int("abc")   # This should handle the ValueError

Conversion successful. Integer value: 123
Error: Could not convert to integer. Invalid input!

## Requirement 16

In [17]:
def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print("Error: Division by zero!")
    else:
        print("Division result:", result)
    finally:
        print("Division operation completed.")

# Example usage of the divide function
divide(10, 2)  # This should print the division result
print("--------------------")
divide(8, 0)   # This should handle the ZeroDivisionError

Division result: 5.0
Division operation completed.
--------------------
Error: Division by zero!
Division operation completed.

In [18]:
def open_and_read_file(file_path):
    try:
        # Attempt to open the file
        file = open(r"c:\Users\lethi\assignment-05.ipynb", 'r')  # Prefix the string with 'r' to treat it as a raw string
    except FileNotFoundError:
        # Handle the case when the file is not found
        print(f"Error: File 'c:/Users/lethi/assignment-05.ipynb' not found!")
    except IOError:
        # Handle other I/O errors
        print("Error: Unable to read the file.")
    else:
        # Read the contents of the file
        print("File opened successfully. Contents:")
        for line in file:
            print(line.strip())
        file.close()
    finally:
        # Close the file regardless of whether an exception occurred or not
        print("Closing the file.")

# Example usage of the open_and_read_file function
open_and_read_file("nonexistent_file.txt")  # This should handle FileNotFoundError
print("--------------------")
open_and_read_file("example.txt")  # This should open and read the file if it exists

File opened successfully. Contents:
{
"cells": [
{
"cell_type": "markdown",
"id": "44c2e300",
"metadata": {},
"source": [
"# This is Assignment 05 - Thienkim Le"
]
},
{
"cell_type": "markdown",
"id": "b0a6b60e",
"metadata": {},
"source": [
"## Requirement 4"
]
},
{
"cell_type": "code",
"execution_count": 16,
"id": "c4487a12",
"metadata": {
"scrolled": true
},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"4 = 2 + 2\n",
"5 = 7 - 2\n",
"24 = 4 * 6\n",
"3.75 = 15 / 4\n",
"3 = 15 // 4\n",
"64 = 4 ** 3\n"
]
}
],
"source": [
"# Demonstrate arithmetic operations\n",
"x = 2 + 2\n",
"print(x, \"= 2 + 2\")\n",
"x = 7 - 2\n",
"print(x, \"= 7 - 2\")\n",
"x = 4 * 6\n",
"print(x, \"= 4 * 6\")\n",
"x = 15 / 4\n",
"print(x, \"= 15 / 4\")\n",
"x = 15 // 4\n",
"print(x, \"= 15 // 4\")\n",
"x = 4 ** 3\n",
"print(x, \"= 4 ** 3\")"
]
},
{
"cell_type": "markdown",
"id": "8eab6c99",
"metadata": {},
"source": [
"## Requirement 5"
]
},
{
"cell_type": "code",
"execution_count": 9,
"id": "abb9f881",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"5  equal to  5\n",
"5  not equal to  9\n",
"9  greater than  5\n",
"5  less than  9\n",
"5  less than or equal to  9\n",
"5  greater than or equal to  5\n"
]
}
],
"source": [
"# Demonstrate the following comparison operations in a cell\n",
"a = 5\n",
"b = 5\n",
"c = 9\n",
"a==b\n",
"print(a, \" equal to \", b)\n",
"a!=b\n",
"print(a, \" not equal to \", c)\n",
"c>b\n",
"print(c, \" greater than \", b)\n",
"b<c\n",
"print(b, \" less than \", c)\n",
"a<=c\n",
"print(a, \" less than or equal to \", c)\n",
"a>=b\n",
"print(a, \" greater than or equal to \", b)"
]
},
{
"cell_type": "markdown",
"id": "05fcbd36",
"metadata": {},
"source": [
"## Requirement 6"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "90d7858c",
"metadata": {
"scrolled": true
},
"outputs": [],
"source": [
"import operators"
]
},
{
"cell_type": "markdown",
"id": "163d7ee8",
"metadata": {},
"source": [
"This is the operators module."
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "4d24f667",
"metadata": {},
"outputs": [],
"source": [
"!python operators.py"
]
},
{
"cell_type": "markdown",
"id": "1510449c",
"metadata": {},
"source": [
"This is the operators.py"
]
},
{
"cell_type": "markdown",
"id": "d45ff069",
"metadata": {},
"source": [
"## Requirement 7"
]
},
{
"cell_type": "code",
"execution_count": 17,
"id": "bfccbf3d",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"Even numbers: [2, 14, 30, 42, 64, 80, 8, 22, 40, 62, 86]\n",
"Odd numbers: [7, 23, 51, 73, 3, 15, 31, 53, 77]\n"
]
}
],
"source": [
"# Create two lists, list_1 and list_2, and populate them with arbitrary numbers\n",
"list_1 = [2, 7, 14, 23, 30, 42, 51, 64, 73, 80]  # Some even and odd numbers\n",
"list_2 = [3, 8, 15, 22, 31, 40, 53, 62, 77, 86]  # Some even and odd numbers\n",
"# Create two empty lists, list_even and list_odd\n",
"list_even = []\n",
"list_odd = []\n",
"\n",
"# Populate list_even with even numbers from list_1 and list_2\n",
"for num in list_1 + list_2:  # Concatenate both lists to iterate over all numbers\n",
"    if num % 2 == 0:  # Check if the number is even\n",
"        list_even.append(num)\n",
"\n",
"# Populate list_odd with odd numbers from list_1 and list_2\n",
"for num in list_1 + list_2:  # Concatenate both lists to iterate over all numbers\n",
"    if num % 2 != 0:  # Check if the number is odd\n",
"        list_odd.append(num)\n",
"\n",
"# Print list_even and list_odd\n",
"print(\"Even numbers:\", list_even)\n",
"print(\"Odd numbers:\", list_odd)"
]
},
{
"cell_type": "markdown",
"id": "b0886190",
"metadata": {},
"source": [
"## Requirement 8"
]
},
{
"cell_type": "code",
"execution_count": 19,
"id": "bc231bcc",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"5 is an integer.\n",
"7.2 is not an integer.\n",
"-10 is an integer.\n",
"3.0 is not an integer.\n",
"15.5 is not an integer.\n",
"-2.8 is not an integer.\n"
]
}
],
"source": [
"# Define a list containing various numbers\n",
"numbers = [5, 7.2, -10, 3.0, 15.5, -2.8]\n",
"\n",
"# Iterate through the list and test each number\n",
"for num in numbers:\n",
"    if isinstance(num, int):\n",
"        print(f\"{num} is an integer.\")\n",
"    else:\n",
"        print(f\"{num} is not an integer.\")"
]
},
{
"cell_type": "code",
"execution_count": 1,
"id": "d71f5db8",
"metadata": {},
"outputs": [
{
"ename": "AttributeError",
"evalue": "'int' object has no attribute 'is_integer'",
"output_type": "error",
"traceback": [
"\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
"\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
"Cell \u001b[1;32mIn[1], line 6\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;66;03m# Test each number if it's an integer or not\u001b[39;00m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m num \u001b[38;5;129;01min\u001b[39;00m numbers:\n\u001b[1;32m----> 6\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m num\u001b[38;5;241m.\u001b[39mis_integer():\n\u001b[0;32m      7\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m is an integer.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m      8\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n",
"\u001b[1;31mAttributeError\u001b[0m: 'int' object has no attribute 'is_integer'"
]
}
],
"source": [
"# Define some numbers\n",
"numbers = [5, 5.0, 5.5, -10, -10.0, -10.5]\n",
"\n",
"# Test each number if it's an integer or not\n",
"for num in numbers:\n",
"    if num.is_integer():\n",
"        print(f\"{num} is an integer.\")\n",
"    else:\n",
"        print(f\"{num} is not an integer.\")\n"
]
},
{
"cell_type": "markdown",
"id": "de259b63",
"metadata": {},
"source": [
"## Requirement 9"
]
},
{
"cell_type": "code",
"execution_count": 2,
"id": "e81c52f7",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"False\n",
"True\n",
"False\n",
"True\n",
"True\n",
"True\n",
"True\n",
"0x203798b0bc0\n",
"0x203798b0bc0\n"
]
}
],
"source": [
"# Boolean operations\n",
"print(True and False)  # False\n",
"print(True or False)   # True\n",
"print(not True)        # False\n",
"\n",
"# Identity operations\n",
"x = 10\n",
"y = 10\n",
"z = 20\n",
"print(x is y)          # True, because x and y reference the same object with value 10\n",
"print(x is not z)      # True, because x and z reference different objects with different values\n",
"\n",
"# Membership operations\n",
"lst = [1, 2, 3, 4, 5]\n",
"print(1 in lst)        # True, because 1 is present in the list\n",
"print(6 not in lst)    # True, because 6 is not present in the list\n",
"\n",
"# Object Identity\n",
"a = [1, 2, 3]\n",
"b = a\n",
"print(hex(id(a)))      # Hexadecimal address of object a\n",
"print(hex(id(b)))      # Hexadecimal address of object b, which is the same as a since they reference the same object\n"
]
},
{
"cell_type": "markdown",
"id": "b9bf4638",
"metadata": {},
"source": [
"## Requirement 10"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "271f5662",
"metadata": {},
"outputs": [],
"source": [
"from decimal import Decimal, getcontext\n",
"# Using default precision\n",
"a = Decimal('1.1')\n",
"b = Decimal('2.2')\n",
"c = a + b\n",
"print(c)  # Output: 3.3\n",
"\n",
"# Setting a higher precision\n",
"getcontext().prec = 10  # Setting precision to 10 digits\n",
"d = Decimal('1.1111111111')\n",
"e = Decimal('2.2222222222')\n",
"f = d + e\n",
"print(f)  # Output: 3.3333333333\n",
"\n",
"# Setting a lower precision\n",
"getcontext().prec = 3  # Setting precision to 3 digits\n",
"g = Decimal('1.111')\n",
"h = Decimal('2.222')\n",
"i = g + h\n",
"print(i)  # Output: 3.33"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "2f319886",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "d8420bd6",
"metadata": {},
"source": [
"## Requirement 11"
]
},
{
"cell_type": "code",
"execution_count": 4,
"id": "e8c90065",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"Length of the string: 11\n",
"Uppercase: HELLO WORLD\n",
"Capitalized: Hello world\n",
"Concatenated string: Hello World\n",
"Multi-concatenated string: HelloHelloHello\n",
"First character: h\n",
"Last character: d\n"
]
}
],
"source": [
"# Define a string\n",
"my_string = \"hello world\"\n",
"\n",
"# Length of the string\n",
"print(\"Length of the string:\", len(my_string))  # Output: 11\n",
"\n",
"# Convert the string to uppercase\n",
"print(\"Uppercase:\", my_string.upper())  # Output: HELLO WORLD\n",
"\n",
"# Capitalize the first character of the string\n",
"print(\"Capitalized:\", my_string.capitalize())  # Output: Hello world\n",
"\n",
"# Concatenation of strings\n",
"string1 = \"Hello\"\n",
"string2 = \"World\"\n",
"concatenated_string = string1 + \" \" + string2\n",
"print(\"Concatenated string:\", concatenated_string)  # Output: Hello World\n",
"\n",
"# Multi-concatenation\n",
"multi_concatenated_string = string1 * 3\n",
"print(\"Multi-concatenated string:\", multi_concatenated_string)  # Output: HelloHelloHello\n",
"\n",
"# Access individual characters\n",
"print(\"First character:\", my_string[0])  # Output: h\n",
"print(\"Last character:\", my_string[-1])  # Output: d\n"
]
},
{
"cell_type": "markdown",
"id": "5eef8402",
"metadata": {},
"source": [
"## Personal Reflection on Assignment 05\n",
"\n",
"Working on Assignment 05 was an insightful experience. I particularly enjoyed exploring the various string operations and practicing with different Python functionalities. While some challenges arose, such as debugging concatenation issues, overcoming them provided valuable learning opportunities. Overall, this assignment enhanced my understanding of string manipulation in Python and strengthened my programming skills.\n"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "6d5cef0d",
"metadata": {},
"outputs": [],
"source": []
}
],
"metadata": {
"kernelspec": {
"display_name": "Python 3 (ipykernel)",
"language": "python",
"name": "python3"
},
"language_info": {
"codemirror_mode": {
"name": "ipython",
"version": 3
},
"file_extension": ".py",
"mimetype": "text/x-python",
"name": "python",
"nbconvert_exporter": "python",
"pygments_lexer": "ipython3",
"version": "3.11.5"
}
},
"nbformat": 4,
"nbformat_minor": 5
}
Closing the file.
--------------------
File opened successfully. Contents:
{
"cells": [
{
"cell_type": "markdown",
"id": "44c2e300",
"metadata": {},
"source": [
"# This is Assignment 05 - Thienkim Le"
]
},
{
"cell_type": "markdown",
"id": "b0a6b60e",
"metadata": {},
"source": [
"## Requirement 4"
]
},
{
"cell_type": "code",
"execution_count": 16,
"id": "c4487a12",
"metadata": {
"scrolled": true
},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"4 = 2 + 2\n",
"5 = 7 - 2\n",
"24 = 4 * 6\n",
"3.75 = 15 / 4\n",
"3 = 15 // 4\n",
"64 = 4 ** 3\n"
]
}
],
"source": [
"# Demonstrate arithmetic operations\n",
"x = 2 + 2\n",
"print(x, \"= 2 + 2\")\n",
"x = 7 - 2\n",
"print(x, \"= 7 - 2\")\n",
"x = 4 * 6\n",
"print(x, \"= 4 * 6\")\n",
"x = 15 / 4\n",
"print(x, \"= 15 / 4\")\n",
"x = 15 // 4\n",
"print(x, \"= 15 // 4\")\n",
"x = 4 ** 3\n",
"print(x, \"= 4 ** 3\")"
]
},
{
"cell_type": "markdown",
"id": "8eab6c99",
"metadata": {},
"source": [
"## Requirement 5"
]
},
{
"cell_type": "code",
"execution_count": 9,
"id": "abb9f881",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"5  equal to  5\n",
"5  not equal to  9\n",
"9  greater than  5\n",
"5  less than  9\n",
"5  less than or equal to  9\n",
"5  greater than or equal to  5\n"
]
}
],
"source": [
"# Demonstrate the following comparison operations in a cell\n",
"a = 5\n",
"b = 5\n",
"c = 9\n",
"a==b\n",
"print(a, \" equal to \", b)\n",
"a!=b\n",
"print(a, \" not equal to \", c)\n",
"c>b\n",
"print(c, \" greater than \", b)\n",
"b<c\n",
"print(b, \" less than \", c)\n",
"a<=c\n",
"print(a, \" less than or equal to \", c)\n",
"a>=b\n",
"print(a, \" greater than or equal to \", b)"
]
},
{
"cell_type": "markdown",
"id": "05fcbd36",
"metadata": {},
"source": [
"## Requirement 6"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "90d7858c",
"metadata": {
"scrolled": true
},
"outputs": [],
"source": [
"import operators"
]
},
{
"cell_type": "markdown",
"id": "163d7ee8",
"metadata": {},
"source": [
"This is the operators module."
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "4d24f667",
"metadata": {},
"outputs": [],
"source": [
"!python operators.py"
]
},
{
"cell_type": "markdown",
"id": "1510449c",
"metadata": {},
"source": [
"This is the operators.py"
]
},
{
"cell_type": "markdown",
"id": "d45ff069",
"metadata": {},
"source": [
"## Requirement 7"
]
},
{
"cell_type": "code",
"execution_count": 17,
"id": "bfccbf3d",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"Even numbers: [2, 14, 30, 42, 64, 80, 8, 22, 40, 62, 86]\n",
"Odd numbers: [7, 23, 51, 73, 3, 15, 31, 53, 77]\n"
]
}
],
"source": [
"# Create two lists, list_1 and list_2, and populate them with arbitrary numbers\n",
"list_1 = [2, 7, 14, 23, 30, 42, 51, 64, 73, 80]  # Some even and odd numbers\n",
"list_2 = [3, 8, 15, 22, 31, 40, 53, 62, 77, 86]  # Some even and odd numbers\n",
"# Create two empty lists, list_even and list_odd\n",
"list_even = []\n",
"list_odd = []\n",
"\n",
"# Populate list_even with even numbers from list_1 and list_2\n",
"for num in list_1 + list_2:  # Concatenate both lists to iterate over all numbers\n",
"    if num % 2 == 0:  # Check if the number is even\n",
"        list_even.append(num)\n",
"\n",
"# Populate list_odd with odd numbers from list_1 and list_2\n",
"for num in list_1 + list_2:  # Concatenate both lists to iterate over all numbers\n",
"    if num % 2 != 0:  # Check if the number is odd\n",
"        list_odd.append(num)\n",
"\n",
"# Print list_even and list_odd\n",
"print(\"Even numbers:\", list_even)\n",
"print(\"Odd numbers:\", list_odd)"
]
},
{
"cell_type": "markdown",
"id": "b0886190",
"metadata": {},
"source": [
"## Requirement 8"
]
},
{
"cell_type": "code",
"execution_count": 19,
"id": "bc231bcc",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"5 is an integer.\n",
"7.2 is not an integer.\n",
"-10 is an integer.\n",
"3.0 is not an integer.\n",
"15.5 is not an integer.\n",
"-2.8 is not an integer.\n"
]
}
],
"source": [
"# Define a list containing various numbers\n",
"numbers = [5, 7.2, -10, 3.0, 15.5, -2.8]\n",
"\n",
"# Iterate through the list and test each number\n",
"for num in numbers:\n",
"    if isinstance(num, int):\n",
"        print(f\"{num} is an integer.\")\n",
"    else:\n",
"        print(f\"{num} is not an integer.\")"
]
},
{
"cell_type": "code",
"execution_count": 1,
"id": "d71f5db8",
"metadata": {},
"outputs": [
{
"ename": "AttributeError",
"evalue": "'int' object has no attribute 'is_integer'",
"output_type": "error",
"traceback": [
"\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
"\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
"Cell \u001b[1;32mIn[1], line 6\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;66;03m# Test each number if it's an integer or not\u001b[39;00m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m num \u001b[38;5;129;01min\u001b[39;00m numbers:\n\u001b[1;32m----> 6\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m num\u001b[38;5;241m.\u001b[39mis_integer():\n\u001b[0;32m      7\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m is an integer.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m      8\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n",
"\u001b[1;31mAttributeError\u001b[0m: 'int' object has no attribute 'is_integer'"
]
}
],
"source": [
"# Define some numbers\n",
"numbers = [5, 5.0, 5.5, -10, -10.0, -10.5]\n",
"\n",
"# Test each number if it's an integer or not\n",
"for num in numbers:\n",
"    if num.is_integer():\n",
"        print(f\"{num} is an integer.\")\n",
"    else:\n",
"        print(f\"{num} is not an integer.\")\n"
]
},
{
"cell_type": "markdown",
"id": "de259b63",
"metadata": {},
"source": [
"## Requirement 9"
]
},
{
"cell_type": "code",
"execution_count": 2,
"id": "e81c52f7",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"False\n",
"True\n",
"False\n",
"True\n",
"True\n",
"True\n",
"True\n",
"0x203798b0bc0\n",
"0x203798b0bc0\n"
]
}
],
"source": [
"# Boolean operations\n",
"print(True and False)  # False\n",
"print(True or False)   # True\n",
"print(not True)        # False\n",
"\n",
"# Identity operations\n",
"x = 10\n",
"y = 10\n",
"z = 20\n",
"print(x is y)          # True, because x and y reference the same object with value 10\n",
"print(x is not z)      # True, because x and z reference different objects with different values\n",
"\n",
"# Membership operations\n",
"lst = [1, 2, 3, 4, 5]\n",
"print(1 in lst)        # True, because 1 is present in the list\n",
"print(6 not in lst)    # True, because 6 is not present in the list\n",
"\n",
"# Object Identity\n",
"a = [1, 2, 3]\n",
"b = a\n",
"print(hex(id(a)))      # Hexadecimal address of object a\n",
"print(hex(id(b)))      # Hexadecimal address of object b, which is the same as a since they reference the same object\n"
]
},
{
"cell_type": "markdown",
"id": "b9bf4638",
"metadata": {},
"source": [
"## Requirement 10"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "271f5662",
"metadata": {},
"outputs": [],
"source": [
"from decimal import Decimal, getcontext\n",
"# Using default precision\n",
"a = Decimal('1.1')\n",
"b = Decimal('2.2')\n",
"c = a + b\n",
"print(c)  # Output: 3.3\n",
"\n",
"# Setting a higher precision\n",
"getcontext().prec = 10  # Setting precision to 10 digits\n",
"d = Decimal('1.1111111111')\n",
"e = Decimal('2.2222222222')\n",
"f = d + e\n",
"print(f)  # Output: 3.3333333333\n",
"\n",
"# Setting a lower precision\n",
"getcontext().prec = 3  # Setting precision to 3 digits\n",
"g = Decimal('1.111')\n",
"h = Decimal('2.222')\n",
"i = g + h\n",
"print(i)  # Output: 3.33"
]
},
{
"cell_type": "code",
"execution_count": null,
"id": "2f319886",
"metadata": {},
"outputs": [],
"source": []
},
{
"cell_type": "markdown",
"id": "d8420bd6",
"metadata": {},
"source": [
"## Requirement 11"
]
},
{
"cell_type": "code",
"execution_count": 4,
"id": "e8c90065",
"metadata": {},
"outputs": [
{
"name": "stdout",
"output_type": "stream",
"text": [
"Length of the string: 11\n",
"Uppercase: HELLO WORLD\n",
"Capitalized: Hello world\n",
"Concatenated string: Hello World\n",
"Multi-concatenated string: HelloHelloHello\n",
"First character: h\n",
"Last character: d\n"
]
}
],
"source": [
"# Define a string\n",
"my_string = \"hello world\"\n",
"\n",
"# Length of the string\n",
"print(\"Length of the string:\", len(my_string))  # Output: 11\n",
"\n",
"# Convert the string to uppercase\n",
"print(\"Uppercase:\", my_string.upper())  # Output: HELLO WORLD\n",
"\n",
"# Capitalize the first character of the string\n",
"print(\"Capitalized:\", my_string.capitalize())  # Output: Hello world\n",
"\n",
"# Concatenation of strings\n",
"string1 = \"Hello\"\n",
"string2 = \"World\"\n",
"concatenated_string = string1 + \" \" + string2\n",
"print(\"Concatenated string:\", concatenated_string)  # Output: Hello World\n",
"\n",
"# Multi-concatenation\n",
"multi_concatenated_string = string1 * 3\n",
"print(\"Multi-concatenated string:\", multi_concatenated_string)  # Output: HelloHelloHello\n",
"\n",
"# Access individual characters\n",
"print(\"First character:\", my_string[0])  # Output: h\n",

## Requirement 17

Iterator indirection refers to the process of indirectly accessing elements in a sequence through an iterator object rather than directly accessing the elements themselves. In Python, when iterating over a sequence like a list or a tuple, an iterator object is used to keep track of the current position in the sequence and provide access to the elements sequentially. Instead of directly accessing elements by index or position, the iterator object abstracts away the details of the underlying data structure and provides a consistent interface for accessing elements. This indirection allows for more flexible and efficient iteration, especially when dealing with large or complex data structures, and promotes code reusability and clarity by providing a unified approach to iterating over different types of sequences.

## Requirement 18

In [22]:
# Create a list of 10 animal species
animals_list = ["Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Bear", "Wolf", "Hippo", "Rhino", "Kangaroo"]

# Get the length of the animals_list using len()
list_length = len(animals_list)

# Print the length of the list
print("Length of animals_list:", list_length)

# Iterate over the range of indices and print the index and corresponding animal
for i in range(list_length):
    print(f"Index {i}: {animals_list[i]}")

Length of animals_list: 10
Index 0: Lion
Index 1: Tiger
Index 2: Elephant
Index 3: Giraffe
Index 4: Zebra
Index 5: Bear
Index 6: Wolf
Index 7: Hippo
Index 8: Rhino
Index 9: Kangaroo

## Requirement 19

In [20]:
# Create a list of animal species
animals_list = ["Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Monkey", "Kangaroo", "Penguin", "Dolphin", "Crocodile"]

# Print the length of the list
print("Length of animals_list:", len(animals_list))

# Iterate over the list to print index and values of animals using enumerate
print("Index  Animal")
for index, animal in enumerate(animals_list):
    print(f"{index:5}  {animal}")

Length of animals_list: 10
Index  Animal
    0  Lion
    1  Tiger
    2  Elephant
    3  Giraffe
    4  Zebra
    5  Monkey
    6  Kangaroo
    7  Penguin
    8  Dolphin
    9  Crocodile

## Requirement 20

In [23]:
# Create a list of 10 colors
colors_list = ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", "Black", "White", "Gray"]

# Use the zip iterator to iterate over both lists simultaneously
for animal, color in zip(animals_list, colors_list):
    print(f"Animal: {animal}, Color: {color}")

Animal: Lion, Color: Red
Animal: Tiger, Color: Orange
Animal: Elephant, Color: Yellow
Animal: Giraffe, Color: Green
Animal: Zebra, Color: Blue
Animal: Bear, Color: Indigo
Animal: Wolf, Color: Violet
Animal: Hippo, Color: Black
Animal: Rhino, Color: White
Animal: Kangaroo, Color: Gray

## Requirement 21

In [24]:
# Define the lambda function
times_ten = lambda x: x * 10

# Use the map iterator with range(10) to apply the lambda to each value
# in the range and print the results
for result in map(times_ten, range(10)):
    print(result)

0
10
20
30
40
50
60
70
80
90

## Requirement 22

In [25]:
# Define the lambda function
by_three = lambda x: x % 3 == 0

# Use the filter iterator with range(30) to filter out values
# that are not evenly divisible by 3 and print the results
filtered_values = filter(by_three, range(30))
for value in filtered_values:
    print(value)

0
3
6
9
12
15
18
21
24
27

## Requirement 23

Working on Assignment 06 was a valuable learning experience for me. It provided an opportunity to practice and deepen my understanding of various Python concepts, such as iterators, lambda functions, and exception handling. Additionally, solving the tasks in this assignment helped me improve my problem-solving skills and gain confidence in applying Python programming techniques to real-world scenarios. Overall, I found Assignment 06 to be challenging yet rewarding, and I look forward to continuing my exploration of Python programming in future assignments.